#!/bin/bash
# This script will start Pd in nogui
# mode and will open the patch
# named "nicorette.pd"
echo "Starting Pd..."
#pd -nogui /home/pi/Desktop/nicorette.pd &
pd-extended -rt -oss -r 48000 -nogui -nomidi bakamod.pd &

